version: 2
sources:
  - name: trulens
    database: "trulens"
    schema: public
    tables:
      - name: trulens_records
      - name: trulens_feedbacks

  - name: frontend
    database: "trulens"
    schema: frontend
    tables:
      - name: record_id_clicks