analytics:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('TRULENS_HOST', 'trulens') }}"
      port: "{{ env_var('TRULENS_PORT', 5432) | int }}"
      user: "{{ env_var('TRULENS_USER', 'postgres') }}"
      pass: "{{ env_var('TRULENS_PASSWORD', 'root') }}"
      dbname: "postgres"
      schema: public
  target: dev

analytics_v2:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('TRULENS_HOST', 'trulens') }}"
      port: "{{ env_var('TRULENS_PORT', 5432) | int }}"
      user: "{{ env_var('TRULENS_USER', 'postgres') }}"
      pass: "{{ env_var('TRULENS_PASSWORD', 'root') }}"
      dbname: "trulens"
      schema: public
  target: dev
