FROM apache/airflow:2.9.3

# Install any webserver-specific system dependencies if needed
# RUN apt-get update && apt-get install -y <webserver-specific-packages>

USER airflow

# Copy requirements.txt
#COPY requirements.txt /opt/airflow/requirements.txt

# Install Python packages from requirements.txt
#RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

# Set the working directory
WORKDIR /opt/airflow

# Command to run the webserver
CMD ["airflow", "webserver"]
