services:
  db:
    container_name: container-pg
    image: pgvector/pgvector:0.6.1-pg16
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ai_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
