# write docker file to load python and mistral
FROM python:3.12.2-bullseye

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .
# update pip
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8080

# Run your_script_name.py when the container launches
CMD ["python3", "app.py"]