FROM apache/airflow:2.9.2

#ENV HOME=/home/airflow
#ENV AIRFLOW_HOME=/home/airflow

USER airflow

# Install dependencies
RUN pip install --upgrade pip

RUN pip install apache-airflow && pip install psycopg2-binary
#RUN pip install dotenv
# Copy requirements definition to container
COPY ./dags/requirements.txt /dags/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /dags/requirements.txt

CMD ["airflow", "scheduler"]
