FROM apache/airflow:2.9.2

ENV HOME=/home/airflow
ENV AIRFLOW_HOME=/home/airflow

USER airflow

RUN pip install apache-airflow && pip install psycopg2-binary

ENTRYPOINT ["tini", "--", "entrypoint.sh"]
CMD ["airflow", "scheduler"]
