FROM apache/airflow:2.9.2

ENV HOME=/home/airflow
ENV AIRFLOW_HOME=/home/airflow

USER airflow

# Install dependencies
RUN pip install --upgrade pip

RUN pip install apache-airflow && pip install psycopg2-binary

# Copy requirements definition to container
COPY ./requirements.txt /opt/airflow/dags/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /opt/airflow/dags/requirements.txt

CMD ["airflow", "scheduler"]
