services:

  ########################## Postgres #########################################
  postgres:
    container_name: postgres
    image: pgvector/pgvector:0.6.1-pg16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-ai_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1']
      interval: 5s
      timeout: 3s
    networks:
      - zuba
  ########################### End Postgres ####################################

  ########################## AI Interface #########################################

  ai_interface:
    user: root
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./notebooks:/home/jupyternb
    environment:
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-ai_db}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - TRULENS_USER=${TRULENS_USER:-postgres}
      - TRULENS_PASSWORD=${TRULENS_PASSWORD:-root}
      - TRULENS_DB=${TRULENS_DB:-trulens}
      - TRULENS_PORT=${TRULENS_PORT:-5432}
      - TRULENS_HOST=trulens
    working_dir: /home/jupyternb
    ports:
      - '8888:8888'
      - '8501:8501'
    depends_on: 
      - postgres
    networks:
      - zuba

  ########################## AI Interface #########################################

  ##################### AI Performance Tracking ####################################
  trulens:
    container_name: trulens
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${TRULENS_USER:-postgres}
      - POSTGRES_PASSWORD=${TRULENS_PASSWORD:-root}
      - POSTGRES_DB=${TRULENS_DB:-trulens}
    volumes:
      - trulensdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1']
      interval: 5s
      timeout: 3s
    networks:
      - zuba
  ##################### End AI Performance Tracking ################################


  ########################### Networks Definition #############################
networks:
  zuba:
    name: zuba-net
    driver: bridge
  ########################### End Networks Definition #########################

  ########################### Volumes Definition ##############################
volumes:
  pgdata:
  trulensdata:

  ########################### End Volumes Definition ##########################
