services:
  #############################################
  #                Examples/Research          #
  #############################################
  ########################## PGVector Experiment #########################################
  postgres:
    container_name: postgres
    image: pgvector/pgvector:0.6.1-pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-ai_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1",
        ]
      interval: 5s
      timeout: 3s
    networks:
      - zuba
  ########################### End Postgres ####################################

  #########################  Jupyter Notebook #################################
  jupyter_notebook:
    build:
      context: ../examples
      dockerfile: ../examples/Dockerfile
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-ai_db}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      TRULENS_USER: ${TRULENS_USER:-postgres}
      TRULENS_PASSWORD: ${TRULENS_PASSWORD:-root}
      TRULENS_DB: ${TRULENS_DB:-trulens}
      TRULENS_PORT: ${TRULENS_PORT:-5432}
      TRULENS_HOST: trulens
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-12345678}
      NEO4J_DB: ${NEO4J_DB:-bclaws}
      NEO4J_PORT: ${NEO4J_PORT:-7687}
      NEO4J_HOST: neo4j
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8888:8888"
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - ../examples:/app
    networks:
      - zuba
  ########################## End Jupyter Notebook ####################################

  ############################ AIRFLOW #########################################
  airflow_postgres:
    container_name: airflow_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    networks:
      - zuba

  airflow_init:
    container_name: airflow_init
    image: apache/airflow:2.9.3
    depends_on:
      - airflow_postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER:-admin}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD:-admin}
    entrypoint: |
      /bin/bash -c "airflow db init && \
      airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com"
    networks:
      - zuba

  airflow_webserver:
    build:
      context: ../mlops/orchestration/airflow
      dockerfile: .docker/local/Dockerfile.webserver
    container_name: airflow_webserver
    depends_on:
      - airflow_postgres
      - airflow_init
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "13000:8080"
    volumes:
      - ../mlops/orchestration/airflow/dags:/opt/airflow/dags
      - ../mlops/orchestration/airflow/logs:/opt/airflow/logs
      - ../mlops/orchestration/airflow/plugins:/opt/airflow/plugins
      - ../mlops/orchestration/airflow/scripts:/opt/airflow/scripts
      - ../mlops/orchestration/airflow/data:/opt/airflow/data
    networks:
      - zuba
    command: ["airflow", "webserver"]

  airflow_scheduler:
    build:
      context: ../mlops/orchestration/airflow
      dockerfile: .docker/local/Dockerfile.scheduler
    container_name: airflow_scheduler
    depends_on:
      - airflow_postgres
      - airflow_init
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      NEO4J_USERNAME: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-12345678}
      NEO4J_DB: ${NEO4J_DB:-neo4j}
      NEO4J_PORT: ${NEO4J_PORT:-7687}
      NEO4J_HOST: neo4j
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZURE_AI_ENDPOINT: ${AZURE_AI_ENDPOINT}
      AZURE_AI_KEY: ${AZURE_AI_KEY}
      TRULENS_USER: ${TRULENS_USER:-postgres}
      TRULENS_PASSWORD: ${TRULENS_PASSWORD:-root}
      TRULENS_PORT: ${TRULENS_PORT:-5432}
      TRULENS_HOST: trulens
      TRULENS_DB: ${TRULENS_DB:-trulens}
      APP_DB: ${APP_DB:-postgres}
    volumes:
      - ../mlops/orchestration/airflow/dags:/opt/airflow/dags
      - ../mlops/orchestration/airflow/logs:/opt/airflow/logs
      - ../mlops/orchestration/airflow/plugins:/opt/airflow/plugins
      - ../mlops/orchestration/airflow/scripts:/opt/airflow/scripts
      - ../mlops/orchestration/airflow/data:/opt/airflow/data
      - ../mlops/orchestration/dbt:/opt/airflow/dbt
      - ../web/backend-fastapi/analytics_data:/opt/airflow/analytics_data/
    networks:
      - zuba
    command: ["airflow", "scheduler"]

  ocp_airflow_scheduler:
    build:
      context: ../mlops/orchestration/airflow
      dockerfile: .docker/ocp/Dockerfile.scheduler
    command: ["airflow", "scheduler"]

  ocp_airflow_webserver:
    build:
      context: ../mlops/orchestration/airflow
      dockerfile: .docker/ocp/Dockerfile.webserver
    command: ["airflow", "webserver"]

  ############################ End of AIRFLOW ##################################

  ##################### AI Performance Tracking ################################
  trulens:
    container_name: trulens
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TRULENS_USER:-postgres}
      POSTGRES_PASSWORD: ${TRULENS_PASSWORD:-root}
      POSTGRES_DB: ${TRULENS_DB:-trulens}
    volumes:
      - trulensdata:/var/lib/postgresql/data
    ports:
      - "5433:${TRULENS_PORT:-5432}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1",
        ]
      interval: 5s
      timeout: 3s
    networks:
      - zuba
  ##################### End AI Performance Tracking ################################

  ######################## NEO4J ###############################################
  neo4j:
    container_name: citz-imb-ai-neo4j-svc
    image: neo4j:latest
    restart: unless-stopped
    environment:
      - USERNAME=${NEO4J_USER:-neo4j}
      - PASSWORD=${NEO4J_PASSWORD:-12345678}
      - DB=${NEO4J_DB:-bclaws}
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j:/var/lib/neo4j/data
      - neo4j-backup:/var/lib/neo4j/backups
    ports:
      - "${NEO4J_DASHBOARD_PORT:-7474}:7474"
      - "${NEO4J_PORT:-7687}:7687"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -d $${NEO4J_DB} -U $${NEO4J_USER} || exit 1"]
      interval: 5s
      timeout: 3s
    networks:
      - zuba
  ######################## End NEO4J ############################################

  ######################## web FRONTEND ############################################
  web_frontend:
    container_name: citz-imb-ai-frontend-svc
    build:
      context: ../web/frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - web_backend
    ports:
      - "8080:8080"
    networks:
      - zuba
  ######################## End of web FRONTEND #####################################

  ##################### WEB FRONTEND FEEDBACK ANALYTICS ############################
  web_frontend_feedback_analytics:
    container_name: feedback_analytics
    build:
      context: ../web/frontend-feedback-analytics
      dockerfile: Dockerfile
    ports:
      - "11000:11000"
    networks:
      - zuba
  ##################### End WEB FRONTEND FEEDBACK ANALYTICS ############################

  ########################## WEB BACKEND ############################################
  web_backend:
    container_name: citz-imb-ai-backend-svc
    build:
      context: ../web/backend-fastapi
      dockerfile: Dockerfile
    environment:
      TRULENS_USER: ${TRULENS_USER:-postgres}
      TRULENS_PASSWORD: ${TRULENS_PASSWORD:-root}
      TRULENS_DB: ${TRULENS_DB:-trulens}
      TRULENS_PORT: ${TRULENS_PORT:-5432}
      TRULENS_HOST: trulens
      APP_DB: ${APP_DB:-postgres}
      NEO4J_USERNAME: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-12345678}
      NEO4J_DB: ${NEO4J_DB:-neo4j}
      NEO4J_PORT: ${NEO4J_PORT:-7687}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZURE_AI_ENDPOINT: ${AZURE_AI_ENDPOINT}
      AZURE_AI_KEY: ${AZURE_AI_KEY}
    depends_on:
      - trulens
      - neo4j
    ports:
      - "10000:10000"
    volumes:
      - ../web/backend-fastapi/analytics_data:/backend/analytics_data/
    networks:
      - zuba
  ######################## End WEB BACKEND ############################################

  ########################## WEB BACKEND DEV ############################################
  web_backend_dev:
    container_name: citz-imb-ai-backend-dev
    build:
      context: ../web/backend-fastapi
      dockerfile: Dockerfile
      target: dev
    environment:
      TRULENS_USER: ${TRULENS_USER:-postgres}
      TRULENS_PASSWORD: ${TRULENS_PASSWORD:-root}
      TRULENS_DB: ${TRULENS_DB:-trulens}
      TRULENS_PORT: ${TRULENS_PORT:-5432}
      TRULENS_HOST: trulens
      APP_DB: ${APP_DB:-postgres}
      NEO4J_USERNAME: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-12345678}
      NEO4J_DB: ${NEO4J_DB:-neo4j}
      NEO4J_PORT: ${NEO4J_PORT:-7687}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZURE_AI_ENDPOINT: ${AZURE_AI_ENDPOINT}
      AZURE_AI_KEY: ${AZURE_AI_KEY}
      FASTAPI_ENV: development
    ports:
      - "10000:10000"
    volumes:
      - ../web/backend-fastapi:/backend
      - ../web/backend-fastapi/analytics_data:/backend/analytics_data/
    networks:
      - zuba
  ######################## End WEB BACKEND DEV ############################################

  ########################## trulens ############################
  trulens_dashboard:
    container_name: citz-imb-ai-trulens-dashboard-svc
    build:
      context: ../web/trulens-dashboard
      dockerfile: Dockerfile
    environment:
      TRULENS_USER: ${TRULENS_USER:-postgres}
      TRULENS_PASSWORD: ${TRULENS_PASSWORD:-root}
      TRULENS_DB: ${TRULENS_DB:-trulens}
      TRULENS_PORT: ${TRULENS_PORT:-5432}
      TRULENS_HOST: trulens
    ports:
      - "14000:14000"
    networks:
      - zuba

  ######################## End of trulens #####################################

  ######################## pgAdmin ############################################
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - "9099:80"
    depends_on:
      - postgres
      - trulens
      - neo4j
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - zuba
  ######################## End of pgAdmin #####################################

  ######################## AWS CREDS CRON #####################################
  aws_creds_cron:
    build:
      context: .
      dockerfile: Dockerfile.awscron

  ######################## END OF AWS CREDS CRON #####################################

  ######################## LLM SERVER (llama.cpp + Intel oneAPI) ##################
  # Local LLM inference with OpenAI-compatible API
  # Uses llama.cpp built with Intel oneAPI MKL for AVX-512/AMX acceleration
  #
  # Usage:
  #   docker compose -f .docker/compose.controller.yaml up llm_server
  #   MODELS=1,7 docker compose -f .docker/compose.controller.yaml up llm_server
  #
  # Models:
  #   1=Qwen2.5-3B(:8090) 2=Qwen3VL-4B(:8091) 3=GLM4.6V(:8092)
  #   4=KimiVL(:8093) 5=Devstral24B(:8094) 6=Qwen2-0.5B(:8095) 7=Qwen3-8B(:8096)
  #   8=Qwen3VL-8B(:8097)
  #
  # API: http://localhost:<port>/v1/chat/completions
  llm_server:
    container_name: citz-imb-ai-llm-svc
    build:
      context: .
      dockerfile: Dockerfile.llamacpp
      args:
        BUILD_PRESET: ${LLM_BUILD_PRESET:-portable}
    environment:
      MODELS: ${LLM_MODELS:-8}
      CONTEXT_SIZE: ${LLM_CONTEXT_SIZE:-4096}
      THREADS: ${LLM_THREADS:-}
      DOWNLOAD_MODELS: ${LLM_DOWNLOAD_MODELS:-true}
      MODEL_SOURCE_DIR: /models
      REQUIRE_AVX512: ${LLM_REQUIRE_AVX512:-false}
      HF_TOKEN: ${HF_TOKEN:-}
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
      - "8097:8097"
    volumes:
      - llm_models:/models
    healthcheck:
      test: ["CMD-SHELL", "for p in 8090 8091 8092 8093 8094 8095 8096 8097; do curl -sf \"http://localhost:$${p}/health\" && exit 0; done; exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 3
    restart: unless-stopped
    networks:
      - zuba
  ######################## End LLM SERVER ##########################################

########################### Networks Definition ################################
networks:
  zuba:
    name: zuba-net
    driver: bridge
########################### End Networks Definition #########################

########################### Volumes Definition ##############################
volumes:
  pgdata:
  trulensdata:
  neo4j:
  neo4j-backup:
  pgadmin_data:
  airflow_pgdata:
  airflow_logs:
  analytics_data:
  llm_models:
########################### End Volumes Definition ##########################
