# GitHub Actions workflow for building and tagging images
name: AWS Creds Cron Image Build and Push

on:
  workflow_dispatch

jobs:
  # Job to build, tag, and push the APP image
  build-tag-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to BC Gov OCP ImageStream
    - name: Login to OCP
      run : |
        docker login ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_TOOLS_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

    # Build the image
    - name: Build Image
      run: |
        docker compose -f ${{ vars.COMPOSE_FILE_NAME }} build aws_creds_cron

    # Tag the image
    - name: Tag Image
      run: |
        docker tag docker-aws_creds_cron ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/aws-creds-cron-imagestream:latest

    # Push the image
    - name: Push Image
      run: |
        docker push ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/aws-creds-cron-imagestream:latest

