name: Sync DAGs to OCP Volume

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '/mlops/orchestration/airflow/dags/**'  # Only trigger when DAG files change

jobs:
  sync-dags:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install `oc`
    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvzf oc.tar.gz
        chmod +x oc
        mkdir -p $HOME/bin
        mv oc $HOME/bin/
        echo "$HOME/bin" >> $GITHUB_PATH

    # Verify `oc`
    - name: Check `oc` version
      run: oc version

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_DEV_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}
        insecure_skip_tls_verify: true

    # Get Generated Pod Name
    - name: Get Pod Name
      run: |
        POD_NAME=$(oc get pods -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} -l role=airflow-webserver --no-headers -o custom-columns=":metadata.name")
        echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

    # Sync DAGs to OCP Airflow volume
    - name: Sync DAGs to OCP Volume
      run: |
        oc rsync ./mlops/orchestration/airflow/dags/ ${{ env.POD_NAME }}:/opt/airflow/dags -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} --delete
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 23 ]; then
          echo "Ignoring `rsync` permission error"
          exit 0
        else
          exit $EXIT_CODE
        fi

    - name: Verify DAGs transfer
      run: |
        oc exec ${{ env.POD_NAME }} -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} -- ls -l /opt/airflow/dags

