name: Sync DAGs to OCP Volume

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '/mlops/orchestration/airflow/dags/**'  # Only trigger when DAG files change

jobs:
  sync-dags:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_DEV_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}
        insecure_skip_tls_verify: true

    # Get Generated Pod Name
    - name: Get Pod Name
      run: |
        POD_NAME=$(oc get pods -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} -l role=airflow-webserver --no-headers -o custom-columns=":metadata.name")
        echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

    # Sync DAGs to OCP Airflow volume
    - name: Sync DAGs to OCP Volume
      run: |

        oc rsync ./mlops/orchestration/airflow/dags/ ${{ env.POD_NAME }}:/opt/airflow/dags -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} --delete

    - name: Verify DAGs transfer
      run: |
        oc exec ${{ env.POD_NAME }} -n ${{ secrets.OPENSHIFT_DEV_NAMESPACE }} -- ls -l /opt/airflow/dags

