# GitHub Actions workflow for building and tagging the APP image on PR
name: DEV Backend Build and Push on PR

on:
  pull_request:
    types:
    - opened
    - synchronize
    - ready_for_review
    branches:
    - main
    paths:
      - web/backend-fastapi/**

jobs:
  # Job to build, tag, and push the APP image
  app-build-tag-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}

    # Login to BC Gov Artifactory Docker Image Repository
    - name: Login to Artifactory
      run : |
        docker login ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }} -u ${{ secrets.ARTIFACTORY_SA_NAME }} -p ${{ secrets.ARTIFACTORY_SA_PASSWORD }}

    # Build the APP image
    - name: Build APP Image
      run: |
        docker-compose -f ${{ vars.COMPOSE_FILE_NAME }} build web_backend

    # Tag the APP image
    - name: Tag APP Image
      run: |
        docker tag docker_web_backend ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }}/ai-fastapi:${{github.event.pull_request.number}}

    # Push the APP image
    - name: Push APP Image
      run: |
        docker push ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }}/ai-fastapi:${{ github.event.pull_request.number }}

