# GitHub Actions workflow for building and tagging the APP image on PR
name: DEV App Build on PR

on:
  pull_request:
    types:
    - opened
    - synchronize
    - ready_for_review
    branches:
    - main

jobs:
  # Job to build, tag, and push the APP image
  app-build-tag-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}

    # Login to BC Gov Artifactory Docker Image Repository
    - name: Login to Artifactory
      run : |
        docker login ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }} -u ${{ secrets.ARTIFACTORY_SA_NAME }} -p ${{ secrets.ARTIFACTORY_SA_PASSWORD }}

    # Build the APP image
    - name: Build APP Image
      run: |
        docker-compose -f ${{ vars.COMPOSE_FILE_NAME }} build ${{ vars.APP_NAME }}

    # Tag the APP image
    - name: Tag APP Image
      run: |
        docker tag docker_${{ vars.APP_NAME }} ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }}/zuba-app:${{github.event.pull_request.number}}

    # Push the APP image
    - name: Push APP Image
      run: |
        docker push ${{ secrets.ARTIFACTORY_IMAGE_REPOSITORY }}/zuba-app:${{ github.event.pull_request.number }}

  update-gitops-image-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Install yq
      run: |
        curl -Lo yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
        chmod +x yq
        mv yq /home/runner/bin

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Clone, Update, and Commit Changes
      run: |
        git clone git@github.com:bcgov-c/tenant-gitops-b875cc.git
        cd tenant-gitops-b875cc

        FILE_PATH="citz-imb-ai/values.yaml"
        NEW_TAG="${{ github.event.pull_request.number }}"

        yq e ".backend.image.tag = \"$NEW_TAG\"" -i "$FILE_PATH"

        git config user.email "brandon.bouchard@gov.bc.ca"
        git config user.name "Bottle7"

        git add "$FILE_PATH"
        git commit -m "Update backend image tag to $NEW_TAG"
        git push

