# GitHub Actions workflow for building and tagging the APP image on PR
name: Frontend Analytics Build and Push on PR

on:
  pull_request:
    types:
    - opened
    - synchronize
    - ready_for_review
    branches:
    - main
    paths:
      - web/frontend-feedback-analytics/**

jobs:
  # Job to build, tag, and push the image
  build-tag-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}

    # Login to BC Gov Artifactory Docker Image Repository
    - name: Login to Artifactory
      run : |
        docker login ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_TOOLS_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

    # Build the image
    - name: Build Image
      run: |
        docker compose -f ${{ vars.COMPOSE_FILE_NAME }} build web_frontend_feedback_analytics

    # Tag the image
    - name: Tag Image
      run: |
        docker tag docker_web_frontend_feedback_analytics ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/ai-frontend-analytics-imagestream:${{github.event.pull_request.number}}

    # Push the image
    - name: Push Image
      run: |
        docker push ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/ai-frontend-analytics-imagestream:${{ github.event.pull_request.number }}

