# GitHub Actions workflow for building and tagging the APP image on PR
name: OCP Airflow Scheduler Build and Push

on:
  workflow_dispatch

jobs:
  # Job to build, tag, and push the APP image
  build-tag-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Login to the Openshift Cluster
    - name: Login to Openshift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}

    # Login to BC Gov Artifactory Docker Image Repository
    - name: Login to Artifactory
      run : |
        docker login ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_TOOLS_NAME }} -p ${{ secrets.OPENSHIFT_SA_TOOLS_TOKEN }}

    # Build the image
    - name: Build Image
      run: |
        docker-compose -f ${{ vars.COMPOSE_FILE_NAME }} build ocp_airflow_scheduler

    # Tag the image
    - name: Tag Image
      run: |
        docker tag docker_ocp_airflow_scheduler ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/airflow-scheduler-imagestream:latest

    # Push the image
    - name: Push Image
      run: |
        docker push ${{ secrets.OPENSHIFT_IMAGE_REPOSITORY }}/airflow-scheduler-imagestream:latest

